### ISSUE TITLE
Anomaly log file type detection and predict future log error

### ISSUE THREAD

**Issue by khawar-islam** [LogIntelligence/LogPPT#2]
Dear @vanhoanglepsa 

Thank you for your work. I have to indirect question and if you can answer I will be thankful to you!

How we can recognize log file type?
How we can predict future log analysis error based on current log data?

**Comment by vanhoanglepsa** [comment]
Hi @khawar-islam 

This project aims at parsing unstructured log data into log templates associated with parameters.
To predict errors/faults from logs, you can refer to other works such as:
1. [loglizer](https://github.com/logpai/loglizer)
2. [LogAD](https://github.com/LogIntelligence/LogADEmpirical)
