### ISSUE TITLE
When I finished running $Python fewshot sampling. py, I couldn't find test.json

### ISSUE THREAD

**Issue by superfeimao** [LogIntelligence/LogPPT#4]
When I finished running $Python fewshot sampling. py, I couldn't find test.json。

FileNotFoundError: Unable to find '/home/featurize/LogPPT-master/datasets/Apache/test.json' at /home/featurize/LogPPT-master

Can you help me?

**Comment by lijinlus** [comment]
same problem ，can you help pls

**Comment by vanhoanglepsa** [comment]
Hi @superfeimao , @lijinlus 

Please refer to #3 to solve this problem.
